// Content Engine orchestrator — generation runs on GLM-5.2 (tier-2), fed by the data core.
// Opus orchestrates; GLM drafts. Prices are INJECTED from the data core (cited) so GLM never
// invents them. Output stays DRAFT + human-gated (/build-os/10). Fills gap cells (query gaps).
//   NVIDIA_API_KEY=... node --experimental-sqlite data-core/gen_content.mjs
import { generate } from "../integrations/glm_generate.mjs";
import { open, logRun } from "./db.mjs";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const db = open();

// Fill ALL remaining gap cells (query gaps), each in the market's primary language.
// Non-English drafts are flagged for native QA (T007) before publish.
const LANGNAME = { en:"English", ar:"Arabic", am:"Amharic", my:"Burmese", sw:"Swahili" };
const BATCH = db.prepare(`
  SELECT cm.category_id catId, cm.market_code mk FROM category_market cm
  JOIN category c ON c.id=cm.category_id JOIN market m ON m.code=cm.market_code
  WHERE c.status='launch'
    AND NOT EXISTS (SELECT 1 FROM content_asset ca WHERE ca.category_id=cm.category_id AND ca.market_code=cm.market_code)
  ORDER BY m.tier, cm.category_id`).all().map(r => [r.catId, r.mk]);

const SYSTEM = "You are a careful medical-travel SEO writer for a FACILITATOR (not a hospital). " +
  "Absolute rules: never invent prices/outcomes/accreditations; use ONLY the prices provided; " +
  "no cure or outcome guarantees; include a facilitator disclaimer; plain, warm, trustworthy English. " +
  "Output GitHub-flavoured Markdown only.";

const slug = (c, mk, lang) => `${c}-cost-india-${mk.toLowerCase()}${lang !== "en" ? "-" + lang : ""}.md`;

for (const [catId, mk] of BATCH) {
  const cat = db.prepare(`SELECT * FROM category WHERE id=?`).get(catId);
  const market = db.prepare(`SELECT * FROM market WHERE code=?`).get(mk);
  const lang = JSON.parse(market.languages)[0];
  const langName = LANGNAME[lang] || "English";
  const prices = db.prepare(`SELECT * FROM category_price WHERE category_id=? ORDER BY india_low`).all(catId);
  const priceLines = prices.map(p =>
    `- ${p.procedure}: $${p.india_low.toLocaleString()}–${p.india_high.toLocaleString()} (vs ${p.comparator})`).join("\n");
  const langLine = lang === "en"
    ? "Language: English."
    : `Write the ENTIRE page in ${langName} (${lang})${lang === "ar" ? ", right-to-left" : ""}. Keep the price figures as USD numerals. This draft will get native-speaker QA before publish.`;

  const prompt = `Write a cornerstone SEO landing page: "${cat.name} treatment cost in India for patients from ${market.name}".
Audience: patients in ${market.name} considering treatment in India. ${langLine}
Use EXACTLY these India international-patient package prices (do not change, do not add others):
${priceLines}
Structure: H1 title; a one-line "In short" summary; "Why patients from ${market.name} choose India" (3-4 bullets incl. cost saving, accredited JCI/NABH hospitals, short waits); a Markdown cost table (procedure | India package | reference); a simple 5-step patient journey (WhatsApp reports -> free teleconsult + quote -> e-Medical Visa -> travel/stay -> follow-up); a short FAQ (safety, length of stay, payment direct to hospital); and a closing WhatsApp call-to-action.
Start with an HTML comment: <!-- DRAFT · generated by GLM-5.2 · cell ${catId}×${mk} (${lang}) · needs ${lang !== "en" ? "native QA + " : ""}clinical sign-off -->
Include one line stating we are a facilitator, not a provider, and that prices are indicative pending assessment. Keep it ~450-600 words.`;

  process.stdout.write(`GLM-5.2 drafting ${catId}×${mk} (${lang}) … `);
  let md;
  try { md = await generate(prompt, { system: SYSTEM, maxTokens: 3000, temperature: 0.6 }); }
  catch (e) { console.log("FAILED:", String(e).slice(0, 120)); logRun(db, "Content Engine", `draft ${catId}×${mk} (${lang})`, "GLM error: " + String(e).slice(0,80), null, "fail"); continue; }

  const file = join("outputs", "content", slug(catId, mk, lang));
  const qaNote = lang !== "en" ? " NEEDS NATIVE-SPEAKER QA (non-English)." : "";
  const header = `<!-- Content Engine · GLM-5.2 (tier-2) · fed by data core · ${new Date().toISOString().slice(0,10)}\n` +
    `     Prices injected from data core (cited /build-os/08). Prose is GLM-generated → DRAFT, needs human+clinical sign-off.${qaNote} -->\n\n`;
  writeFileSync(join(ROOT, file), header + md.trim() + "\n");

  const info = db.prepare(`INSERT INTO content_asset (category_id,market_code,language,title,file_ref,status,cta_wired,citations_ok)
    VALUES (?,?,?,?,?, 'draft', 0, 0)`)
    .run(catId, mk, lang, `${cat.name} Cost in India — ${market.name} Guide (GLM draft, ${lang})`, file);
  logRun(db, "Content Engine", `draft ${catId}×${mk} (${lang})`, `${md.length} chars${qaNote}`, `/draft/${info.lastInsertRowid}`, "ok");
  console.log(`ok -> ${file} (${md.length} chars)${qaNote}`);
}

const n = db.prepare(`SELECT count(*) c FROM content_asset`).get().c;
console.log(`\nContent assets now: ${n}. New drafts are status=draft, citations_ok=0 (verify prose + wire CTA before publish).`);
db.close();
